kind: pipeline
type: docker
name: default

steps:
  - name: ✅ Test
    image: node
    commands:
      - yarn install
      - yarn build
      - yarn test

  - name: 📦 Publish
    image: plugins/docker
    settings:
      repo: mauriceo/viewtube
      tags:
        - latest
        - '0.5.0'
        - '0.5'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - stable
      event:
        - push

  - name: 🧪 Publish dev
    image: plugins/docker
    settings:
      repo: mauriceo/viewtube
      tags:
        - dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - development
      event:
        - push

  - name: 🔔 Notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_bot_token
      to: -1001411660806
    when:
      branch:
        - stable
      event:
        - push
      status:
        - success
        - failure

trigger:
  branch:
    - stable
    - development
