---
clone:
  depth: 1
kind: pipeline
name: pull-request
steps:
- commands:
  - yarn install
  image: node:16
  name: install
  pull: if-not-exists
  volumes:
  - name: installcache
    path: /installcache
- commands:
  - yarn build:client
  depends_on:
  - install
  image: node:16
  name: build-client
  pull: if-not-exists
  volumes:
  - name: installcache
    path: /installcache
- commands:
  - yarn build:server
  depends_on:
  - install
  image: node:16
  name: build-server
  pull: if-not-exists
  volumes:
  - name: installcache
    path: /installcache
- commands:
  - yarn test
  depends_on:
  - install
  image: mauriceo/nodejs-mongodb:1.0
  name: test
  pull: if-not-exists
  volumes:
  - name: installcache
    path: /installcache
trigger:
  branch:
  - development
  event:
  - pull_request
type: docker
volumes:
- name: installcache
  temp: {}
---
clone:
  depth: 1
kind: pipeline
name: build-amd64
platform:
  arch: amd64
  os: linux
steps:
- depends_on:
  - test
  image: plugins/docker
  name: publish-stable
  pull: if-not-exists
  settings:
    cache_from: mauriceo/viewtube:latest
    compress: "true"
    password:
      from_secret: docker_password
    repo: mauriceo/viewtube
    tags:
    - latest
    - 0.9.0
    - "0.9"
    username:
      from_secret: docker_username
  when:
    branch:
    - stable
    event:
    - push
- depends_on:
  - test
  image: plugins/docker
  name: publish-development
  pull: if-not-exists
  settings:
    cache_from: mauriceo/viewtube:dev
    compress: "true"
    password:
      from_secret: docker_password
    repo: mauriceo/viewtube
    tags:
    - dev
    username:
      from_secret: docker_username
  when:
    branch:
    - development
    event:
    - push
trigger:
  branch:
  - development
  - stabe
  event:
  - push
type: docker
---
clone:
  depth: 1
kind: pipeline
name: build-arm64
platform:
  arch: arm64
  os: linux
steps:
- depends_on:
  - test
  image: plugins/docker
  name: publish-stable
  pull: if-not-exists
  settings:
    cache_from: mauriceo/viewtube:latest
    compress: "true"
    password:
      from_secret: docker_password
    repo: mauriceo/viewtube
    tags:
    - latest
    - 0.9.0
    - "0.9"
    username:
      from_secret: docker_username
  when:
    branch:
    - stable
    event:
    - push
- depends_on:
  - test
  image: plugins/docker
  name: publish-development
  pull: if-not-exists
  settings:
    cache_from: mauriceo/viewtube:dev
    compress: "true"
    password:
      from_secret: docker_password
    repo: mauriceo/viewtube
    tags:
    - dev
    username:
      from_secret: docker_username
  when:
    branch:
    - development
    event:
    - push
trigger:
  branch:
  - development
  - stabe
  event:
  - push
type: docker
---
depends_on:
- build-amd64
- build-arm64
kind: pipeline
name: manifest-dev
steps:
- image: plugins/manifest
  name: manifest
  settings:
    ignore_missing: "true"
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    target: mauriceo/viewtube:dev
    template: mauriceo/viewtube:dev-OS-ARCH
    username:
      from-secret: docker_username
trigger:
  branch:
  - development
  event:
  - push
type: docker
---
depends_on:
- build-amd64
- build-arm64
kind: pipeline
name: manifest-latest
steps:
- image: plugins/manifest
  name: manifest
  settings:
    ignore_missing: "true"
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    target: mauriceo/viewtube:latest
    template: mauriceo/viewtube:latest-OS-ARCH
    username:
      from-secret: docker_username
trigger:
  branch:
  - stable
  event:
  - push
type: docker
---
depends_on:
- build-amd64
- build-arm64
kind: pipeline
name: manifest-0.9.0
steps:
- image: plugins/manifest
  name: manifest
  settings:
    ignore_missing: "true"
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    target: mauriceo/viewtube:0.9.0
    template: mauriceo/viewtube:0.9.0-OS-ARCH
    username:
      from-secret: docker_username
trigger:
  branch:
  - stable
  event:
  - push
type: docker
---
depends_on:
- build-amd64
- build-arm64
kind: pipeline
name: manifest-0.9
steps:
- image: plugins/manifest
  name: manifest
  settings:
    ignore_missing: "true"
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    target: mauriceo/viewtube:0.9
    template: mauriceo/viewtube:0.9-OS-ARCH
    username:
      from-secret: docker_username
trigger:
  branch:
  - stable
  event:
  - push
type: docker
