yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@nestjs/swagger@^5.1.0":
    peerDependencies:
      typescript: "^4.4.3"
  "middie@*":
    dependencies:
      fastify: "*"
  "nuxt@*":
    peerDependencies:
      consola: "*"
  "fork-ts-checker-webpack-plugin@^6.3.3":
    peerDependencies:
      vue-template-compiler: "^2.6.14"
      eslint: "^7.32.0"
  "@nuxt/typescript-build@^2.1.0":
    peerDependencies:
      vue-template-compiler: "^2.6.14"
  #     eslint: "^7.32.0"
      webpack: "^4.4.3"
  "@nuxt/babel-preset-app@^2.15.8":
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "^7.15.4"
  # "eslint-plugin-prettier@^4.0.0":
  #   peerDependencies:
  #     prettier: "^2.4.1"
  "eslint-plugin-jest@^24.5.0":
    peerDependencies:
      typescript: "^4.4.3"
  # "@typescript-eslint/eslint-plugin@^4.32.0":
  #   peerDependencies:
  #     typescript: "^4.4.3"
  "vue-eslint-parser@^7.11.0":
    dependencies:
      "@typescript-eslint/parser": "^4.32.0"
      typescript: "^4.4.3"
  "@typescript-eslint/typescript-estree@^4.32.0":
    peerDependencies:
      typescript: "^4.4.3"
  "@nuxtjs/eslint-config-typescript@^6.0.1":
    peerDependencies:
      typescript: "^4.4.3"
  "@typescript-eslint/experimental-utils@^4.32.0":
    peerDependencies:
      typescript: "^4.4.3"
