defaultSemverRangePrefix: ""

packageExtensions:
  "@fastify/cookie@^6.0.0":
    peerDependencies:
      fastify: ^3.22.0
  "@fastify/helmet@^8.0.0":
    peerDependencies:
      fastify: ^3.22.0
  "@fastify/multipart@^6.0.0":
    peerDependencies:
      fastify: ^3.22.0
  "@nestjs/swagger@^5.1.0":
    peerDependencies:
      class-transformer: "*"
      class-validator: "*"
      typescript: ^4.4.3
  "@typescript-eslint/typescript-estree@^4.32.0":
    peerDependencies:
      typescript: ^4.4.3
  eslint-plugin-jest@^24.5.0:
    peerDependencies:
      typescript: ^4.4.3
  middie@*:
    dependencies:
      fastify: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpIgnorePatterns:
  - ./client/**

yarnPath: .yarn/releases/yarn-3.1.1.cjs
