yarnPath: '.yarn/releases/yarn-berry.cjs'
packageExtensions:
  autoprefixer@*:
    peerDependencies:
      postcss: '^8.3.0'
  nuxt-typed-vuex@^0.2.0:
    peerDependencies:
      '@nuxt/types': '^2.15.0'