packageExtensions:
  "@nestjs/swagger@^5.1.0":
    peerDependencies:
      typescript: ^4.4.3
      class-transformer: "*"
      class-validator: "*"
  "@nuxt/babel-preset-app@^2.15.8":
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": ^7.15.4
      debug: ^4.3.2
      encoding: ^0.1.13
      supports-color: ^9.0.2
  "@nuxt/typescript-build@^2.1.0":
    peerDependencies:
      vue-template-compiler: ^2.6.14
      webpack: ^4.4.3
  run-script-webpack-plugin@^0.0.11:
    peerDependencies:
      webpack: ^4.4.3
  "@nuxtjs/eslint-config-typescript@^6.0.1":
    peerDependencies:
      typescript: ^4.4.3
  "@typescript-eslint/experimental-utils@^4.32.0":
    peerDependencies:
      typescript: ^4.4.3
  "@typescript-eslint/typescript-estree@^4.32.0":
    peerDependencies:
      typescript: ^4.4.3
  eslint-plugin-jest@^24.5.0:
    peerDependencies:
      typescript: ^4.4.3
  fastify-cookie@^5.3.1:
    peerDependencies:
      fastify: ^3.22.0
  fastify-helmet@^5.3.2:
    peerDependencies:
      fastify: ^3.22.0
  fastify-multipart@^5.0.1:
    peerDependencies:
      fastify: ^3.22.0
  fork-ts-checker-webpack-plugin@^6.3.3:
    peerDependencies:
      eslint: ^7.32.0
      vue-template-compiler: ^2.6.14
  middie@*:
    dependencies:
      fastify: "*"
  nuxt@*:
    peerDependencies:
      consola: "*"
  vue-eslint-parser@^7.11.0:
    dependencies:
      "@typescript-eslint/parser": ^4.32.0
      typescript: ^4.4.3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs
