version: "3"

services:
  viewtube-db:
    container_name: viewtube-db
    image: mongo
    networks:
      - viewtube-local
    ports:
      - 27017:27017

  viewtube-redis:
    container_name: viewtube-redis
    image: redis
    networks:
      - viewtube-local
    ports:
      - 6379:6379

  viewtube-nginx:
    container_name: viewtube-nginx
    image: nginx
    volumes:
      - "./scripts/dev/nginx.conf:/etc/nginx/nginx.conf:ro"
    network_mode: host

networks:
  viewtube-local:
    driver: bridge
