name: Build on schedule [nightly]

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-on-push-job:
    uses: './.github/workflows/build-workflow.yml'
    with:
      architectures: |
        linux/amd64
        linux/arm64
        linux/arm/v7
      dev_tag: 'nightly'
    secrets: inherit
