name: Build base workflow

on:
  workflow_call:

jobs:
  create-release:
    name: Create Release

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: moisout/changelog-create-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
