name: Pull Request

on:
  pull_request:
    branches: ["development"]

jobs:
  pr-job:
    continue-on-error: true
    strategy:
      matrix:
        command: ["build:server", "build:client", "test"]

    name: ${{ matrix.command }}
    timeout-minutes: 60
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Node.js PR workflow step ${{ matrix.command }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.0.1
        name: Setup pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          
      - run: pnpm install
      - run: pnpm run ${{ matrix.command }}
