name: Build on push [dev/stable]

on:
  push:
    branches: ['development']
    tags:
      - 'v*'

jobs:
  create-release-job:
    if: github.ref == 'refs/heads/development'
    uses: './github/workflows/create-release-workflow.yml'
    secrets: inherit

  build-development-on-push-job:
    if: github.ref == 'refs/heads/development'
    uses: './.github/workflows/build-workflow.yml'
    with:
      architectures: linux/amd64
    secrets: inherit

  build-stable-on-push-job:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: './.github/workflows/build-workflow.yml'
    with:
      architectures: |
        linux/amd64
        linux/arm64
        linux/arm/v7
    secrets: inherit
